package com.archiving.utils;

/**
 * Tags class, storing the tags lists
 * 
 * @author Maxwell Leu
 */
public class Tags {
    /** Tags for a complete XML file with specific optional information */
    public static String[] tags = {
        "a001",
        "a002",
        "productidentifier",
        "/productidentifier",
        "b221",
        "b244",
        "b012",
        "b211",
        "series",
        "/series",
        "seriesidentifier",
        "/seriesidentifier",
        "b273",
        "b018",
        "b019",
        "title",
        "/title",
        "b202",
        "b203",
        "b368",
        "b369",
        "b370",
        "b029",
        "contributor",
        "/contributor",
        "b035",
        "b340",
        "b036",
        "b037",
        "b039",
        "b040",
        "b057",
        "b058",
        "language",
        "/language",
        "b253",
        "b252",
        "b255",
        "mainsubject",
        "/mainsubject",
        "b191",
        "b068",
        "b069",
        "b070",
        "subject",
        "/subject",
        "b067",
        "othertext",
        "/othertext",
        "d102",
        "d103",
        "d104",
        "d105",
        "d106",
        "relatedproduct",
        "/relatedproduct",
        "h208",
        "publisher",
        "/publisher",
        "b291",
        "b241",
        "b243",
        "b081",
        "b209",
        "b003",
        "supplydetail",
        "/supplydetail",
        "supplieridentifier",
        "/supplieridentifier",
        "j345",
        "j137",
        "j292",
        "j396",
        "j260",
        "j142",
        "price",
        "/price",
        "j148",
        "j266",
        "j151",
        "j152",
        "b251",
        "j153"
    };
    /** Required tags for a complete ProQuest XML */
    public static String[] reqTags = {
        "a001", 
        "a002", 
        "productidentifier", 
        "b221",     
        "b244", 
        "b012",     // -> "DG"      DONE
        "b211",     // -> 02 "PDF"  DONE
        "series", 
        "seriesidentifier", 
        "b273", 
        "b018",     // -> Alternativ zu b202 und b203
        "n338",     // -> alternativ zu "series"
        "title", 
        "b202", 
        "b203", 
        "contributor",  
        "b034", 
        "b035", 
        "b036", 
        "b037", 
        "b047", 
        "b044", 
        "language", 
        "b253", 
        "b252", 
        "mainsubject", 
        "b191", 
        "b068", 
        "b069", 
        "subject", 
        "b067", 
        "b069", 
        "othertext", 
        "d102", 
        "d103", 
        "d104", 
        "imprint", 
        "b079", 
        "publisher", 
        "b291", 
        "b081", 
        "b241", 
        "b243", 
        "b003", 
        "salesrights", 
        "b089", 
        "b090",     // Alternativ zu b388
        "b388",     // Alternativ zu b090
        "relatedproduct", 
        "h208", 
        "productidentifier", 
        "b221", 
        "b244", 
        "b012", 
        "supplydetail", 
        "j141",     // Alternativ/ergaenzend zu j396
        "j396",     // Alternativ/ergaenzend zu j141
        "price", 
        "j148", 
        "j151", 
        "j152", 
        "b251", 
        "j153", 
    };
}
